spring.applicaiton.name: kafka-streams-window
spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams:
  binder.configuration:
    key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  bindings.output.producer:
    keySerde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
spring.cloud.stream.bindings.output:
  destination: shipment-counts
spring.cloud.stream.bindings.input:
  destination: shipments
spring.cloud.stream.kafka.streams.binder:
  brokers: localhost #192.168.99.100
  application-id: blah
#spring.cloud.stream.kafka.streams.binder.application-id: